import ROAD_HERON_BLACK_1 from './HERON_BLACK_1.png';
import ROAD_HERON_BLACK_2 from './HERON_BLACK_2.jpg';
import ROAD_HERON_BLACK_3 from './HERON_BLACK_3.jpg';
import ROAD_HERON_BLACK_4 from './HERON_BLACK_4.jpg';

import ROAD_HERON_BLANC_1 from './ROAD_HERON_BLANC_1.png';
import ROAD_HERON_BLANC_2 from './ROAD_HERON_BLANC_2.jpeg';
import ROAD_HERON_BLANC_3 from './ROAD_HERON_BLANC_3.jpeg';
import ROAD_HERON_BLANC_4 from './ROAD_HERON_BLANC_4.jpeg';
import ROAD_HERON_BLANC_5 from './ROAD_HERON_BLANC_5.jpeg';

import ROAD_HERON_GREY_PRIZM_1 from './ROAD_HERON_GREY_PRIZM_1.png';
import ROAD_HERON_GREY_PRIZM_2 from './ROAD_HERON_GREY_PRIZM_2.jpeg';
import ROAD_HERON_GREY_PRIZM_3 from './ROAD_HERON_GREY_PRIZM_3.jpeg';
import ROAD_HERON_GREY_PRIZM_4 from './ROAD_HERON_GREY_PRIZM_4.jpeg';

import ROAD_RACE_YELLOW_1 from './ROAD_RACE_YELLOW_1.png';
import ROAD_RACE_YELLOW_2 from './ROAD_RACE_YELLOW_2.jpg';
import ROAD_RACE_YELLOW_3 from './ROAD_RACE_YELLOW_3.jpg';
import ROAD_RACE_YELLOW_4 from './ROAD_RACE_YELLOW_4.png';
import ROAD_RACE_YELLOW_5 from './ROAD_RACE_YELLOW_5.jpg';

import ROAD_RACE_BLANC_1 from './ROAD_RACE_BLANC_1.png';
import ROAD_RACE_BLANC_2 from './ROAD_RACE_BLANC_2.png';
import ROAD_RACE_BLANC_3 from './ROAD_RACE_BLANC_3.png';
import ROAD_RACE_BLANC_4 from './ROAD_RACE_BLANC_4.png';
import ROAD_RACE_BLANC_5 from './ROAD_RACE_BLANC_5.png';


import MTB_STATUS_X_BLACK_1 from './MTB_STATUS_X_BLACK_1.png';

import MTB_STROVER_BLACK_1 from './MTB_STATUS_X_BLACK_1.png';
import MTB_STROVER_BLACK_2 from './MTB_STROVER_BLACK_2.jpg';
import MTB_STROVER_BLACK_3 from './MTB_STROVER_BLACK_3.jpg';
import MTB_STROVER_BLACK_4 from './MTB_STROVER_BLACK_4.jpg';
import MTB_STROVER_BLACK_5 from './MTB_STROVER_BLACK_5.jpg';

import MTB_STROVER_BLANC_1 from './MTB_STROVER_BLANC_1.png';
import MTB_STROVER_BLANC_2 from './MTB_STROVER_BLANC_2.jpeg';
import MTB_STROVER_BLANC_3 from './MTB_STROVER_BLANC_3.jpeg';
import MTB_STROVER_BLANC_4 from './MTB_STROVER_BLANC_4.jpeg';
import MTB_STROVER_BLANC_5 from './MTB_STROVER_BLANC_5.jpeg';


import MTB_TROOPER_BLACK_1 from './MTB_TROOPER_BLACK_1.png';
import MTB_TROOPER_BLACK_2 from './MTB_TROOPER_BLACK_2.jpg';
import MTB_TROOPER_BLACK_3 from './MTB_TROOPER_BLACK_3.jpg';
import MTB_TROOPER_BLACK_4 from './MTB_TROOPER_BLACK_4.jpg';
import MTB_TROOPER_BLACK_5 from './MTB_TROOPER_BLACK_5.jpg';


import MTB_TROOPER_BLUE_1 from './MTB_TROOPER_BLUE_1.png';
import MTB_TROOPER_BLUE_2 from './MTB_TROOPER_BLUE_2.jpg';
import MTB_TROOPER_BLUE_3 from './MTB_TROOPER_BLUE_3.jpg';
import MTB_TROOPER_BLUE_4 from './MTB_TROOPER_BLUE_4.jpg';
import MTB_TROOPER_BLUE_5 from './MTB_TROOPER_BLUE_5.jpg';


import MTB_FRISK_BLACK_1 from './MTB_FRISK_BLACK_1.png';
import MTB_FRISK_BLACK_2 from './MTB_FRISK_BLACK_2.jpg';
import MTB_FRISK_BLACK_3 from './MTB_FRISK_BLACK_3.jpg';
import MTB_FRISK_BLACK_4 from './MTB_FRISK_BLACK_4.jpg';
import MTB_FRISK_BLACK_5 from './MTB_FRISK_BLACK_5.jpg';

import MTB_FRISK_RED_1 from './MTB_FRISK_RED_1.png';
import MTB_FRISK_RED_2 from './MTB_FRISK_RED_2.jpg';
import MTB_FRISK_RED_3 from './MTB_FRISK_RED_3.jpg';
import MTB_FRISK_RED_4 from './MTB_FRISK_RED_4.jpg';
import MTB_FRISK_RED_5 from './MTB_FRISK_RED_5.jpg';


import MTB_OFFPATH_BLACK_1 from './MTB_OFFPATH_BLACK_1.png';
import MTB_OFFPATH_BLACK_2 from './MTB_OFFPATH_BLACK_2.jpg';
import MTB_OFFPATH_BLACK_3 from './MTB_OFFPATH_BLACK_3.jpg';
import MTB_OFFPATH_BLACK_4 from './MTB_OFFPATH_BLACK_4.jpg';
import MTB_OFFPATH_BLACK_5 from './MTB_OFFPATH_BLACK_5.jpg';

import MTB_OFFPATH_GREEN_1 from './MTB_OFFPATH_GREEN_1.png';
import MTB_OFFPATH_GREEN_2 from './MTB_OFFPATH_GREEN_2.jpg';
import MTB_OFFPATH_GREEN_3 from './MTB_OFFPATH_GREEN_3.jpg';
import MTB_OFFPATH_GREEN_4 from './MTB_OFFPATH_GREEN_4.jpg';
import MTB_OFFPATH_GREEN_5 from './MTB_OFFPATH_GREEN_5.jpg';


import MTB_STRAY_BLACK_1 from './MTB_STRAY_BLACK_1.png';
import MTB_STRAY_BLACK_2 from './MTB_STRAY_BLACK_2.jpg';
import MTB_STRAY_BLACK_3 from './MTB_STRAY_BLACK_3.jpg';
import MTB_STRAY_BLACK_4 from './MTB_STRAY_BLACK_4.jpg';
import MTB_STRAY_BLACK_5 from './MTB_STRAY_BLACK_5.jpg';

import MTB_STRAY_ORANGE_1 from './MTB_STRAY_ORANGE_1.png';
import MTB_STRAY_ORANGE_2 from './MTB_STRAY_ORANGE_2.jpg';
import MTB_STRAY_ORANGE_3 from './MTB_STRAY_ORANGE_3.jpg';
import MTB_STRAY_ORANGE_4 from './MTB_STRAY_ORANGE_4.jpg';
import MTB_STRAY_ORANGE_5 from './MTB_STRAY_ORANGE_5.jpg';




import HOMME_MAILLOTS_BLUE_1 from './HOMME_MAILLOTS_BLUE_1.png'
import HOMME_MAILLOTS_BLUE_2 from './HOMME_MAILLOTS_BLUE_2.png'
import HOMME_MAILLOTS_BLUE_3 from './HOMME_MAILLOTS_BLUE_3.jpg'
import HOMME_MAILLOTS_BLUE_4 from './HOMME_MAILLOTS_BLUE_4.jpg'
import HOMME_MAILLOTS_BLUE_5 from './HOMME_MAILLOTS_BLUE_5.jpg'


import HOMME_MAILLOTS_BLACK_1 from './HOMME_MAILLOTS_BLACK_1.png'
import HOMME_MAILLOTS_BLACK_2 from './HOMME_MAILLOTS_BLACK_2.png'
import HOMME_MAILLOTS_BLACK_3 from './HOMME_MAILLOTS_BLACK_3.jpg'
import HOMME_MAILLOTS_BLACK_4 from './HOMME_MAILLOTS_BLACK_4.jpg'
import HOMME_MAILLOTS_BLACK_5 from './HOMME_MAILLOTS_BLACK_5.jpg'



import HOMME_PANTALON_BRETELLES_WHITE_1 from './HOMME_PANTALON_BRETELLES_WHITE_1.png';
import HOMME_PANTALON_BRETELLES_WHITE_2 from './HOMME_PANTALON_BRETELLES_WHITE_2.png';
import HOMME_PANTALON_BRETELLES_WHITE_3 from './HOMME_PANTALON_BRETELLES_WHITE_3.png';
import HOMME_PANTALON_BRETELLES_WHITE_4 from './HOMME_PANTALON_BRETELLES_WHITE_4.png';
import HOMME_PANTALON_BRETELLES_WHITE_5 from './HOMME_PANTALON_BRETELLES_WHITE_5.jpg';


import HOMME_PANTALON_BRETELLES_BLACK_1 from './HOMME_PANTALON_BRETELLES_BLACK_1.png';
import HOMME_PANTALON_BRETELLES_BLACK_2 from './HOMME_PANTALON_BRETELLES_BLACK_2.png';
import HOMME_PANTALON_BRETELLES_BLACK_3 from './HOMME_PANTALON_BRETELLES_BLACK_3.png';
import HOMME_PANTALON_BRETELLES_BLACK_4 from './HOMME_PANTALON_BRETELLES_BLACK_4.jpg';
import HOMME_PANTALON_BRETELLES_BLACK_5 from './HOMME_PANTALON_BRETELLES_BLACK_5.jpg';


import HOMME_SWEATS_TSHIRTS_BLACK_1 from './HOMME_SWEATS_TSHIRTS_BLACK_1.png'
import HOMME_SWEATS_TSHIRTS_BLACK_2 from './HOMME_SWEATS_TSHIRTS_BLACK_2.png'
import HOMME_SWEATS_TSHIRTS_BLACK_3 from './HOMME_SWEATS_TSHIRTS_BLACK_3.jpg'
import HOMME_SWEATS_TSHIRTS_BLACK_4 from './HOMME_SWEATS_TSHIRTS_BLACK_4.jpg'


import HOMME_SWEATS_TSHIRTS_PETROLE_1 from './HOMME_SWEATS_TSHIRTS_PETROLE_1.png';
import HOMME_SWEATS_TSHIRTS_PETROLE_2 from './HOMME_SWEATS_TSHIRTS_PETROLE_2.png';
import HOMME_SWEATS_TSHIRTS_PETROLE_3 from './HOMME_SWEATS_TSHIRTS_PETROLE_3.jpg';
import HOMME_SWEATS_TSHIRTS_PETROLE_4 from './HOMME_SWEATS_TSHIRTS_PETROLE_4.jpg';

import HOMME_CASQUETTES_BASIQUES_BLACK_1 from './HOMME_CASQUETTES_BASIQUES_BLACK_1.png'


import HOMME_CASQUETTES_BASIQUES_GRIS_1 from  './HOMME_CASQUETTES_BASIQUES_GRIS_1.png'


import FEMME_MAILLOTS_BLUE_1 from './FEMME_MAILLOTS_BLUE_1.png';
import FEMME_MAILLOTS_BLUE_2 from './FEMME_MAILLOTS_BLUE_2.png';
import FEMME_MAILLOTS_BLUE_3 from './FEMME_MAILLOTS_BLUE_3.jpg';
import FEMME_MAILLOTS_BLUE_4 from './FEMME_MAILLOTS_BLUE_4.jpg';


import FEMME_MAILLOTS_BLACK_1 from './FEMME_MAILLOTS_BLACK_1.png';
import FEMME_MAILLOTS_BLACK_2 from './FEMME_MAILLOTS_BLACK_2.png';
import FEMME_MAILLOTS_BLACK_3 from './FEMME_MAILLOTS_BLACK_3.jpg';
import FEMME_MAILLOTS_BLACK_4 from './FEMME_MAILLOTS_BLACK_4.jpg';


import FEMME_PANTALON_BRETELLES_WHITE_1 from './FEMME_PANTALON_BRETELLES_WHITE_1.png';
import FEMME_PANTALON_BRETELLES_WHITE_2 from './FEMME_PANTALON_BRETELLES_WHITE_2.png';


import FEMME_PANTALON_BRETELLES_BLACK_1 from './FEMME_PANTALON_BRETELLES_BLACK_1.png';
import FEMME_PANTALON_BRETELLES_BLACK_2 from './FEMME_PANTALON_BRETELLES_BLACK_2.jpg';

import FEMME_SWEATS_TSHIRTS_BLACK_1 from './FEMME_SWEATS_TSHIRTS_BLACK_1.png';
import FEMME_SWEATS_TSHIRTS_BLACK_2 from './FEMME_SWEATS_TSHIRTS_BLACK_2.png';
import FEMME_SWEATS_TSHIRTS_BLACK_3 from './FEMME_SWEATS_TSHIRTS_BLACK_3.png';
import FEMME_SWEATS_TSHIRTS_BLACK_4 from './FEMME_SWEATS_TSHIRTS_BLACK_4.png';


import FEMME_SWEATS_TSHIRTS_WHITE_1 from './FEMME_SWEATS_TSHIRTS_WHITE_1.png';
import FEMME_SWEATS_TSHIRTS_WHITE_2 from './FEMME_SWEATS_TSHIRTS_WHITE_2.png';
import FEMME_SWEATS_TSHIRTS_WHITE_3 from './FEMME_SWEATS_TSHIRTS_WHITE_3.png';
import FEMME_SWEATS_TSHIRTS_WHITE_4 from './FEMME_SWEATS_TSHIRTS_WHITE_4.png';



export const images_qasques_ROAD_HERON_BLACK={
    ROAD_HERON_BLACK_1,
    ROAD_HERON_BLACK_2,
    ROAD_HERON_BLACK_3,
    ROAD_HERON_BLACK_4,
}
export const images_qasques_ROAD_HERON_BLANC={
    ROAD_HERON_BLANC_1,
    ROAD_HERON_BLANC_2,
    ROAD_HERON_BLANC_3,
    ROAD_HERON_BLANC_4,
    ROAD_HERON_BLANC_5,
}

export const images_qasques_ROAD_HERON_GREY_PRIZM={
    ROAD_HERON_GREY_PRIZM_1,
    ROAD_HERON_GREY_PRIZM_2,
    ROAD_HERON_GREY_PRIZM_3,
    ROAD_HERON_GREY_PRIZM_4

}
export const images_qasques_ROAD_RACE_YELLOW={
    ROAD_RACE_YELLOW_1,
    ROAD_RACE_YELLOW_2,
    ROAD_RACE_YELLOW_3,
    ROAD_RACE_YELLOW_4,
    ROAD_RACE_YELLOW_5,

}

export const images_qasques_ROAD_RACE_BLANC={
    ROAD_RACE_BLANC_1,
    ROAD_RACE_BLANC_2,
    ROAD_RACE_BLANC_3,
    ROAD_RACE_BLANC_4,
    ROAD_RACE_BLANC_5,
}


export const images_qasques_MTB_STATUS_X_BLACK={
    MTB_STATUS_X_BLACK_1
}

export const images_qasques_MTB_STROVER_BLACK={
    MTB_STROVER_BLACK_1,
    MTB_STROVER_BLACK_2,
    MTB_STROVER_BLACK_3,
    MTB_STROVER_BLACK_4,
    MTB_STROVER_BLACK_5,
}


export const images_qasques_MTB_STROVER_BLANC={
    MTB_STROVER_BLANC_1,
    MTB_STROVER_BLANC_2,
    MTB_STROVER_BLANC_3,
    MTB_STROVER_BLANC_4,
    MTB_STROVER_BLANC_5,

}

export const images_qasques_MTB_TROOPER_BLACK={
    MTB_TROOPER_BLACK_1,
    MTB_TROOPER_BLACK_2,
    MTB_TROOPER_BLACK_3,
    MTB_TROOPER_BLACK_4,
    MTB_TROOPER_BLACK_5,
}


export const images_qasques_MTB_TROOPER_BLUE={
    MTB_TROOPER_BLUE_1,
    MTB_TROOPER_BLUE_2,
    MTB_TROOPER_BLUE_3,
    MTB_TROOPER_BLUE_4,
    MTB_TROOPER_BLUE_5,
}


export const images_qasques_MTB_FRISK_BLACK={
    MTB_FRISK_BLACK_1,
    MTB_FRISK_BLACK_2,
    MTB_FRISK_BLACK_3,
    MTB_FRISK_BLACK_4,
    MTB_FRISK_BLACK_5,
}

export const images_qasques_MTB_FRISK_RED={
    MTB_FRISK_RED_1,
    MTB_FRISK_RED_2,
    MTB_FRISK_RED_3,
    MTB_FRISK_RED_4,
    MTB_FRISK_RED_5,
}

export const images_qasques_MTB_OFFPATH_BLACK={
    MTB_OFFPATH_BLACK_1,
    MTB_OFFPATH_BLACK_2,
    MTB_OFFPATH_BLACK_3,
    MTB_OFFPATH_BLACK_4,
    MTB_OFFPATH_BLACK_5,
    
}

export const images_qasques_MTB_OFFPATH_GREEN={
    MTB_OFFPATH_GREEN_1,
    MTB_OFFPATH_GREEN_2,
    MTB_OFFPATH_GREEN_3,
    MTB_OFFPATH_GREEN_4,
    MTB_OFFPATH_GREEN_5,
}


export const images_qasques_MTB_STRAY_BLACK={
    MTB_STRAY_BLACK_1,
    MTB_STRAY_BLACK_2,
    MTB_STRAY_BLACK_3,
    MTB_STRAY_BLACK_4,
    MTB_STRAY_BLACK_5,
    
}


export const images_qasques_MTB_STRAY_ORANGE={
    MTB_STRAY_ORANGE_1,
    MTB_STRAY_ORANGE_2,
    MTB_STRAY_ORANGE_3,
    MTB_STRAY_ORANGE_4,
    MTB_STRAY_ORANGE_5,

}



export const images_vetements_HOMME_MAILLOTS_BLUE={
    HOMME_MAILLOTS_BLUE_1,
    HOMME_MAILLOTS_BLUE_2,
    HOMME_MAILLOTS_BLUE_3,
    HOMME_MAILLOTS_BLUE_4,
    HOMME_MAILLOTS_BLUE_5
}


export const images_vetements_HOMME_MAILLOTS_BLACK={
    HOMME_MAILLOTS_BLACK_1,
    HOMME_MAILLOTS_BLACK_2,
    HOMME_MAILLOTS_BLACK_3,
    HOMME_MAILLOTS_BLACK_4,
    HOMME_MAILLOTS_BLACK_5,
}


export const images_vetements_HOMME_PANTALON_BRETELLES_WHITE={
    HOMME_PANTALON_BRETELLES_WHITE_1,
    HOMME_PANTALON_BRETELLES_WHITE_2,
    HOMME_PANTALON_BRETELLES_WHITE_3,
    HOMME_PANTALON_BRETELLES_WHITE_4,
    HOMME_PANTALON_BRETELLES_WHITE_5,
}


export const images_vetements_HOMME_PANTALON_BRETELLES_BLACK={
    HOMME_PANTALON_BRETELLES_BLACK_1,
    HOMME_PANTALON_BRETELLES_BLACK_2,
    HOMME_PANTALON_BRETELLES_BLACK_3,
    HOMME_PANTALON_BRETELLES_BLACK_4,
    HOMME_PANTALON_BRETELLES_BLACK_5,

}


export const images_vetements_HOMME_SWEATS_TSHIRTS_BLACK={
    HOMME_SWEATS_TSHIRTS_BLACK_1,
    HOMME_SWEATS_TSHIRTS_BLACK_2,
    HOMME_SWEATS_TSHIRTS_BLACK_3,
    HOMME_SWEATS_TSHIRTS_BLACK_4,
}

export const images_vetements_HOMME_SWEATS_TSHIRTS_PETROLE={
    HOMME_SWEATS_TSHIRTS_PETROLE_1,
    HOMME_SWEATS_TSHIRTS_PETROLE_2,
    HOMME_SWEATS_TSHIRTS_PETROLE_3,
    HOMME_SWEATS_TSHIRTS_PETROLE_4,
}


export const images_vetements_HOMME_CASQUETTES_BASIQUES_BLACK={
    HOMME_CASQUETTES_BASIQUES_BLACK_1
}   


export const images_vetements_HOMME_CASQUETTES_BASIQUES_GRIS={
    HOMME_CASQUETTES_BASIQUES_GRIS_1
}


export const images_vetements_FEMME_MAILLOTS_BLUE={
    FEMME_MAILLOTS_BLUE_1,
    FEMME_MAILLOTS_BLUE_2,
    FEMME_MAILLOTS_BLUE_3,
    FEMME_MAILLOTS_BLUE_4,
}


export const images_vetements_FEMME_MAILLOTS_BLACK={
    FEMME_MAILLOTS_BLACK_1,
    FEMME_MAILLOTS_BLACK_2,
    FEMME_MAILLOTS_BLACK_3,
    FEMME_MAILLOTS_BLACK_4,
}


export const images_vetements_FEMME_PANTALON_BRETELLES_WHITE={
    FEMME_PANTALON_BRETELLES_WHITE_1,
    FEMME_PANTALON_BRETELLES_WHITE_2,
}

export const images_vetements_FEMME_PANTALON_BRETELLES_BLACK={
    FEMME_PANTALON_BRETELLES_BLACK_1,
    FEMME_PANTALON_BRETELLES_BLACK_2,
}


export const images_vetements_FEMME_SWEATS_TSHIRTS_BLACK={
    FEMME_SWEATS_TSHIRTS_BLACK_1,
    FEMME_SWEATS_TSHIRTS_BLACK_2,
    FEMME_SWEATS_TSHIRTS_BLACK_3,
    FEMME_SWEATS_TSHIRTS_BLACK_4,
}

export const images_vetements_FEMME_SWEATS_TSHIRTS_WHITE={
    FEMME_SWEATS_TSHIRTS_WHITE_1,
    FEMME_SWEATS_TSHIRTS_WHITE_2,
    FEMME_SWEATS_TSHIRTS_WHITE_3,
    FEMME_SWEATS_TSHIRTS_WHITE_4,
}