import ROAD_HERON_BLACK_1 from './HERON_BLACK_1.png';
import ROAD_HERON_BLACK_2 from './HERON_BLACK_2.jpg';
import ROAD_HERON_BLACK_3 from './HERON_BLACK_3.jpg';
import ROAD_HERON_BLACK_4 from './HERON_BLACK_4.jpg';

import ROAD_HERON_BLANC_1 from './ROAD_HERON_BLANC_1.png';
import ROAD_HERON_BLANC_2 from './ROAD_HERON_BLANC_2.jpeg';
import ROAD_HERON_BLANC_3 from './ROAD_HERON_BLANC_3.jpeg';
import ROAD_HERON_BLANC_4 from './ROAD_HERON_BLANC_4.jpeg';
import ROAD_HERON_BLANC_5 from './ROAD_HERON_BLANC_5.jpeg';

import ROAD_HERON_GREY_PRIZM_1 from './ROAD_HERON_GREY_PRIZM_1.png';
import ROAD_HERON_GREY_PRIZM_2 from './ROAD_HERON_GREY_PRIZM_2.jpeg';
import ROAD_HERON_GREY_PRIZM_3 from './ROAD_HERON_GREY_PRIZM_3.jpeg';
import ROAD_HERON_GREY_PRIZM_4 from './ROAD_HERON_GREY_PRIZM_4.jpeg';

import ROAD_RACE_YELLOW_1 from './ROAD_RACE_YELLOW_1.png';
import ROAD_RACE_YELLOW_2 from './ROAD_RACE_YELLOW_2.jpg';
import ROAD_RACE_YELLOW_3 from './ROAD_RACE_YELLOW_3.jpg';
import ROAD_RACE_YELLOW_4 from './ROAD_RACE_YELLOW_4.png';
import ROAD_RACE_YELLOW_5 from './ROAD_RACE_YELLOW_5.jpg';

import ROAD_RACE_BLANC_1 from './ROAD_RACE_BLANC_1.png';
import ROAD_RACE_BLANC_2 from './ROAD_RACE_BLANC_2.png';
import ROAD_RACE_BLANC_3 from './ROAD_RACE_BLANC_3.png';
import ROAD_RACE_BLANC_4 from './ROAD_RACE_BLANC_4.png';
import ROAD_RACE_BLANC_5 from './ROAD_RACE_BLANC_5.png';


import MTB_STATUS_X_BLACK_1 from './MTB_STATUS_X_BLACK_1.png';

import MTB_STROVER_BLACK_1 from './MTB_STATUS_X_BLACK_1.png';
import MTB_STROVER_BLACK_2 from './MTB_STROVER_BLACK_2.jpg';
import MTB_STROVER_BLACK_3 from './MTB_STROVER_BLACK_3.jpg';
import MTB_STROVER_BLACK_4 from './MTB_STROVER_BLACK_4.jpg';
import MTB_STROVER_BLACK_5 from './MTB_STROVER_BLACK_5.jpg';

import MTB_STROVER_BLANC_1 from './MTB_STROVER_BLANC_1.png';
import MTB_STROVER_BLANC_2 from './MTB_STROVER_BLANC_2.jpeg';
import MTB_STROVER_BLANC_3 from './MTB_STROVER_BLANC_3.jpeg';
import MTB_STROVER_BLANC_4 from './MTB_STROVER_BLANC_4.jpeg';
import MTB_STROVER_BLANC_5 from './MTB_STROVER_BLANC_5.jpeg';


import MTB_TROOPER_BLACK_1 from './MTB_TROOPER_BLACK_1.png';
import MTB_TROOPER_BLACK_2 from './MTB_TROOPER_BLACK_2.jpg';
import MTB_TROOPER_BLACK_3 from './MTB_TROOPER_BLACK_3.jpg';
import MTB_TROOPER_BLACK_4 from './MTB_TROOPER_BLACK_4.jpg';
import MTB_TROOPER_BLACK_5 from './MTB_TROOPER_BLACK_5.jpg';


import MTB_TROOPER_BLUE_1 from './MTB_TROOPER_BLUE_1.png';
import MTB_TROOPER_BLUE_2 from './MTB_TROOPER_BLUE_2.jpg';
import MTB_TROOPER_BLUE_3 from './MTB_TROOPER_BLUE_3.jpg';
import MTB_TROOPER_BLUE_4 from './MTB_TROOPER_BLUE_4.jpg';
import MTB_TROOPER_BLUE_5 from './MTB_TROOPER_BLUE_5.jpg';


import MTB_FRISK_BLACK_1 from './MTB_FRISK_BLACK_1.png';
import MTB_FRISK_BLACK_2 from './MTB_FRISK_BLACK_2.jpg';
import MTB_FRISK_BLACK_3 from './MTB_FRISK_BLACK_3.jpg';
import MTB_FRISK_BLACK_4 from './MTB_FRISK_BLACK_4.jpg';
import MTB_FRISK_BLACK_5 from './MTB_FRISK_BLACK_5.jpg';

import MTB_FRISK_RED_1 from './MTB_FRISK_RED_1.png';
import MTB_FRISK_RED_2 from './MTB_FRISK_RED_2.jpg';
import MTB_FRISK_RED_3 from './MTB_FRISK_RED_3.jpg';
import MTB_FRISK_RED_4 from './MTB_FRISK_RED_4.jpg';
import MTB_FRISK_RED_5 from './MTB_FRISK_RED_5.jpg';


import MTB_OFFPATH_BLACK_1 from './MTB_OFFPATH_BLACK_1.png';
import MTB_OFFPATH_BLACK_2 from './MTB_OFFPATH_BLACK_2.jpg';
import MTB_OFFPATH_BLACK_3 from './MTB_OFFPATH_BLACK_3.jpg';
import MTB_OFFPATH_BLACK_4 from './MTB_OFFPATH_BLACK_4.jpg';
import MTB_OFFPATH_BLACK_5 from './MTB_OFFPATH_BLACK_5.jpg';

import MTB_OFFPATH_GREEN_1 from './MTB_OFFPATH_GREEN_1.png';
import MTB_OFFPATH_GREEN_2 from './MTB_OFFPATH_GREEN_2.jpg';
import MTB_OFFPATH_GREEN_3 from './MTB_OFFPATH_GREEN_3.jpg';
import MTB_OFFPATH_GREEN_4 from './MTB_OFFPATH_GREEN_4.jpg';
import MTB_OFFPATH_GREEN_5 from './MTB_OFFPATH_GREEN_5.jpg';


import MTB_STRAY_BLACK_1 from './MTB_STRAY_BLACK_1.png';
import MTB_STRAY_BLACK_2 from './MTB_STRAY_BLACK_2.jpg';
import MTB_STRAY_BLACK_3 from './MTB_STRAY_BLACK_3.jpg';
import MTB_STRAY_BLACK_4 from './MTB_STRAY_BLACK_4.jpg';
import MTB_STRAY_BLACK_5 from './MTB_STRAY_BLACK_5.jpg';

import MTB_STRAY_ORANGE_1 from './MTB_STRAY_ORANGE_1.png';
import MTB_STRAY_ORANGE_2 from './MTB_STRAY_ORANGE_2.jpg';
import MTB_STRAY_ORANGE_3 from './MTB_STRAY_ORANGE_3.jpg';
import MTB_STRAY_ORANGE_4 from './MTB_STRAY_ORANGE_4.jpg';
import MTB_STRAY_ORANGE_5 from './MTB_STRAY_ORANGE_5.jpg';




import HOMME_MAILLOTS_BLUE_1 from './HOMME_MAILLOTS_BLUE_1.png'
import HOMME_MAILLOTS_BLUE_2 from './HOMME_MAILLOTS_BLUE_2.png'
import HOMME_MAILLOTS_BLUE_3 from './HOMME_MAILLOTS_BLUE_3.jpg'
import HOMME_MAILLOTS_BLUE_4 from './HOMME_MAILLOTS_BLUE_4.jpg'
import HOMME_MAILLOTS_BLUE_5 from './HOMME_MAILLOTS_BLUE_5.jpg'


import HOMME_MAILLOTS_BLACK_1 from './HOMME_MAILLOTS_BLACK_1.png'
import HOMME_MAILLOTS_BLACK_2 from './HOMME_MAILLOTS_BLACK_2.png'
import HOMME_MAILLOTS_BLACK_3 from './HOMME_MAILLOTS_BLACK_3.jpg'
import HOMME_MAILLOTS_BLACK_4 from './HOMME_MAILLOTS_BLACK_4.jpg'
import HOMME_MAILLOTS_BLACK_5 from './HOMME_MAILLOTS_BLACK_5.jpg'



import HOMME_PANTALON_BRETELLES_WHITE_1 from './HOMME_PANTALON_BRETELLES_WHITE_1.png';
import HOMME_PANTALON_BRETELLES_WHITE_2 from './HOMME_PANTALON_BRETELLES_WHITE_2.png';
import HOMME_PANTALON_BRETELLES_WHITE_3 from './HOMME_PANTALON_BRETELLES_WHITE_3.png';
import HOMME_PANTALON_BRETELLES_WHITE_4 from './HOMME_PANTALON_BRETELLES_WHITE_4.png';
import HOMME_PANTALON_BRETELLES_WHITE_5 from './HOMME_PANTALON_BRETELLES_WHITE_5.jpg';


import HOMME_PANTALON_BRETELLES_BLACK_1 from './HOMME_PANTALON_BRETELLES_BLACK_1.png';
import HOMME_PANTALON_BRETELLES_BLACK_2 from './HOMME_PANTALON_BRETELLES_BLACK_2.png';
import HOMME_PANTALON_BRETELLES_BLACK_3 from './HOMME_PANTALON_BRETELLES_BLACK_3.png';
import HOMME_PANTALON_BRETELLES_BLACK_4 from './HOMME_PANTALON_BRETELLES_BLACK_4.jpg';
import HOMME_PANTALON_BRETELLES_BLACK_5 from './HOMME_PANTALON_BRETELLES_BLACK_5.jpg';


import HOMME_SWEATS_TSHIRTS_BLACK_1 from './HOMME_SWEATS_TSHIRTS_BLACK_1.png'
import HOMME_SWEATS_TSHIRTS_BLACK_2 from './HOMME_SWEATS_TSHIRTS_BLACK_2.png'
import HOMME_SWEATS_TSHIRTS_BLACK_3 from './HOMME_SWEATS_TSHIRTS_BLACK_3.jpg'
import HOMME_SWEATS_TSHIRTS_BLACK_4 from './HOMME_SWEATS_TSHIRTS_BLACK_4.jpg'


import HOMME_SWEATS_TSHIRTS_PETROLE_1 from './HOMME_SWEATS_TSHIRTS_PETROLE_1.png';
import HOMME_SWEATS_TSHIRTS_PETROLE_2 from './HOMME_SWEATS_TSHIRTS_PETROLE_2.png';
import HOMME_SWEATS_TSHIRTS_PETROLE_3 from './HOMME_SWEATS_TSHIRTS_PETROLE_3.jpg';
import HOMME_SWEATS_TSHIRTS_PETROLE_4 from './HOMME_SWEATS_TSHIRTS_PETROLE_4.jpg';

import HOMME_CASQUETTES_BASIQUES_BLACK_1 from './HOMME_CASQUETTES_BASIQUES_BLACK_1.png'


import HOMME_CASQUETTES_BASIQUES_GRIS_1 from  './HOMME_CASQUETTES_BASIQUES_GRIS_1.png'


import FEMME_MAILLOTS_BLUE_1 from './FEMME_MAILLOTS_BLUE_1.png';
import FEMME_MAILLOTS_BLUE_2 from './FEMME_MAILLOTS_BLUE_2.png';
import FEMME_MAILLOTS_BLUE_3 from './FEMME_MAILLOTS_BLUE_3.jpg';
import FEMME_MAILLOTS_BLUE_4 from './FEMME_MAILLOTS_BLUE_4.jpg';


import FEMME_MAILLOTS_BLACK_1 from './FEMME_MAILLOTS_BLACK_1.png';
import FEMME_MAILLOTS_BLACK_2 from './FEMME_MAILLOTS_BLACK_2.png';
import FEMME_MAILLOTS_BLACK_3 from './FEMME_MAILLOTS_BLACK_3.jpg';
import FEMME_MAILLOTS_BLACK_4 from './FEMME_MAILLOTS_BLACK_4.jpg';


import FEMME_PANTALON_BRETELLES_WHITE_1 from './FEMME_PANTALON_BRETELLES_WHITE_1.png';
import FEMME_PANTALON_BRETELLES_WHITE_2 from './FEMME_PANTALON_BRETELLES_WHITE_2.png';


import FEMME_PANTALON_BRETELLES_BLACK_1 from './FEMME_PANTALON_BRETELLES_BLACK_1.png';
import FEMME_PANTALON_BRETELLES_BLACK_2 from './FEMME_PANTALON_BRETELLES_BLACK_2.jpg';

import FEMME_SWEATS_TSHIRTS_BLACK_1 from './FEMME_SWEATS_TSHIRTS_BLACK_1.png';
import FEMME_SWEATS_TSHIRTS_BLACK_2 from './FEMME_SWEATS_TSHIRTS_BLACK_2.png';
import FEMME_SWEATS_TSHIRTS_BLACK_3 from './FEMME_SWEATS_TSHIRTS_BLACK_3.png';
import FEMME_SWEATS_TSHIRTS_BLACK_4 from './FEMME_SWEATS_TSHIRTS_BLACK_4.png';


import FEMME_SWEATS_TSHIRTS_WHITE_1 from './FEMME_SWEATS_TSHIRTS_WHITE_1.png';
import FEMME_SWEATS_TSHIRTS_WHITE_2 from './FEMME_SWEATS_TSHIRTS_WHITE_2.png';
import FEMME_SWEATS_TSHIRTS_WHITE_3 from './FEMME_SWEATS_TSHIRTS_WHITE_3.png';
import FEMME_SWEATS_TSHIRTS_WHITE_4 from './FEMME_SWEATS_TSHIRTS_WHITE_4.png';



import GRAVITY_OLIVE_1 from './GRAVITY_OLIVE_1.png';
import GRAVITY_OLIVE_2 from './GRAVITY_OLIVE_2.png';
import GRAVITY_OLIVE_3 from './GRAVITY_OLIVE_3.png';
import GRAVITY_OLIVE_4 from './GRAVITY_OLIVE_4.png';
import GRAVITY_OLIVE_5 from './GRAVITY_OLIVE_5.png';


import GRAVITY_BLUE_1 from './GRAVITY_BLUE_1.png';
import GRAVITY_BLUE_2 from './GRAVITY_BLUE_2.png';
import GRAVITY_BLUE_3 from './GRAVITY_BLUE_3.png';
import GRAVITY_BLUE_4 from './GRAVITY_BLUE_4.png';
import GRAVITY_BLUE_5 from './GRAVITY_BLUE_5.png';


import RACE_BLANC_1 from './RACE_BLANC_1.png';
import RACE_BLANC_2 from './RACE_BLANC_2.png';
import RACE_BLANC_3 from './RACE_BLANC_3.jpg';
import RACE_BLANC_4 from './RACE_BLANC_4.jpg';


import RACE_BLACK_1 from './RACE_BLACK_1.png';
import RACE_BLACK_2 from './RACE_BLACK_2.png';
import RACE_BLACK_3 from './RACE_BLACK_3.jpg';
import RACE_BLACK_4 from './RACE_BLACK_4.jpg';
import RACE_BLACK_5 from './RACE_BLACK_5.jpg';



import MTB_PEACK_PRO_BLACK_1 from './MTB_PEACK_PRO_BLACK_1.png';
import MTB_PEACK_PRO_BLACK_2 from './MTB_PEACK_PRO_BLACK_2.jpg';
import MTB_PEACK_PRO_BLACK_3 from './MTB_PEACK_PRO_BLACK_3.jpg';
import MTB_PEACK_PRO_BLACK_4 from './MTB_PEACK_PRO_BLACK_4.jpg';
import MTB_PEACK_PRO_BLACK_5 from './MTB_PEACK_PRO_BLACK_5.jpg';


import MTB_PEACK_BLACK_1 from './MTB_PEACK_BLACK_1.png';
import MTB_PEACK_BLACK_2 from './MTB_PEACK_BLACK_2.jpg';
import MTB_PEACK_BLACK_3 from './MTB_PEACK_BLACK_3.jpg';
import MTB_PEACK_BLACK_4 from './MTB_PEACK_BLACK_4.jpg';
import MTB_PEACK_BLACK_5 from './MTB_PEACK_BLACK_5.jpg';


import ALL_TERRAIN_OX_PRO_GREY_1 from './ALL_TERRAIN_OX_PRO_GREY_1.png';
import ALL_TERRAIN_OX_PRO_GREY_2 from './ALL_TERRAIN_OX_PRO_GREY_2.jpg';
import ALL_TERRAIN_OX_PRO_GREY_3 from './ALL_TERRAIN_OX_PRO_GREY_3.jpg';
import ALL_TERRAIN_OX_PRO_GREY_4 from './ALL_TERRAIN_OX_PRO_GREY_4.jpg';
import ALL_TERRAIN_OX_PRO_GREY_5 from './ALL_TERRAIN_OX_PRO_GREY_5.jpg';


import ALL_TERRAIN_OX_GREY_1 from './ALL_TERRAIN_OX_GREY_1.png';
import ALL_TERRAIN_OX_GREY_2 from './ALL_TERRAIN_OX_GREY_2.jpg';
import ALL_TERRAIN_OX_GREY_3 from './ALL_TERRAIN_OX_GREY_3.jpg';
import ALL_TERRAIN_OX_GREY_4 from './ALL_TERRAIN_OX_GREY_4.jpg';
import ALL_TERRAIN_OX_GREY_5 from './ALL_TERRAIN_OX_GREY_5.jpg';



export const images_qasques_ROAD_HERON_BLACK=[
    ROAD_HERON_BLACK_1,
    ROAD_HERON_BLACK_2,
    ROAD_HERON_BLACK_3,
    ROAD_HERON_BLACK_4,
]
export const images_qasques_ROAD_HERON_BLANC=[
    ROAD_HERON_BLANC_1,
    ROAD_HERON_BLANC_2,
    ROAD_HERON_BLANC_3,
    ROAD_HERON_BLANC_4,
    ROAD_HERON_BLANC_5,
]

export const images_qasques_ROAD_HERON_GREY_PRIZM=[
    ROAD_HERON_GREY_PRIZM_1,
    ROAD_HERON_GREY_PRIZM_2,
    ROAD_HERON_GREY_PRIZM_3,
    ROAD_HERON_GREY_PRIZM_4

]
export const images_qasques_ROAD_RACE_YELLOW=[
    ROAD_RACE_YELLOW_1,
    ROAD_RACE_YELLOW_2,
    ROAD_RACE_YELLOW_3,
    ROAD_RACE_YELLOW_4,
    ROAD_RACE_YELLOW_5,

]

export const images_qasques_ROAD_RACE_BLANC=[
    ROAD_RACE_BLANC_1,
    ROAD_RACE_BLANC_2,
    ROAD_RACE_BLANC_3,
    ROAD_RACE_BLANC_4,
    ROAD_RACE_BLANC_5,
]


export const images_qasques_MTB_STATUS_X_BLACK=[
    MTB_STATUS_X_BLACK_1
]

export const images_qasques_MTB_STROVER_BLACK=[
    MTB_STROVER_BLACK_1,
    MTB_STROVER_BLACK_2,
    MTB_STROVER_BLACK_3,
    MTB_STROVER_BLACK_4,
    MTB_STROVER_BLACK_5,
]


export const images_qasques_MTB_STROVER_BLANC=[
    MTB_STROVER_BLANC_1,
    MTB_STROVER_BLANC_2,
    MTB_STROVER_BLANC_3,
    MTB_STROVER_BLANC_4,
    MTB_STROVER_BLANC_5,

]

export const images_qasques_MTB_TROOPER_BLACK=[
    MTB_TROOPER_BLACK_1,
    MTB_TROOPER_BLACK_2,
    MTB_TROOPER_BLACK_3,
    MTB_TROOPER_BLACK_4,
    MTB_TROOPER_BLACK_5,
]


export const images_qasques_MTB_TROOPER_BLUE=[
    MTB_TROOPER_BLUE_1,
    MTB_TROOPER_BLUE_2,
    MTB_TROOPER_BLUE_3,
    MTB_TROOPER_BLUE_4,
    MTB_TROOPER_BLUE_5,
]


export const images_qasques_MTB_FRISK_BLACK=[
    MTB_FRISK_BLACK_1,
    MTB_FRISK_BLACK_2,
    MTB_FRISK_BLACK_3,
    MTB_FRISK_BLACK_4,
    MTB_FRISK_BLACK_5,
]

export const images_qasques_MTB_FRISK_RED=[
    MTB_FRISK_RED_1,
    MTB_FRISK_RED_2,
    MTB_FRISK_RED_3,
    MTB_FRISK_RED_4,
    MTB_FRISK_RED_5,
]

export const images_qasques_MTB_OFFPATH_BLACK=[
    MTB_OFFPATH_BLACK_1,
    MTB_OFFPATH_BLACK_2,
    MTB_OFFPATH_BLACK_3,
    MTB_OFFPATH_BLACK_4,
    MTB_OFFPATH_BLACK_5,
    
]

export const images_qasques_MTB_OFFPATH_GREEN=[
    MTB_OFFPATH_GREEN_1,
    MTB_OFFPATH_GREEN_2,
    MTB_OFFPATH_GREEN_3,
    MTB_OFFPATH_GREEN_4,
    MTB_OFFPATH_GREEN_5,
]


export const images_qasques_MTB_STRAY_BLACK=[
    MTB_STRAY_BLACK_1,
    MTB_STRAY_BLACK_2,
    MTB_STRAY_BLACK_3,
    MTB_STRAY_BLACK_4,
    MTB_STRAY_BLACK_5,
    
]


export const images_qasques_MTB_STRAY_ORANGE=[
    MTB_STRAY_ORANGE_1,
    MTB_STRAY_ORANGE_2,
    MTB_STRAY_ORANGE_3,
    MTB_STRAY_ORANGE_4,
    MTB_STRAY_ORANGE_5,

]



export const images_vetements_HOMME_MAILLOTS_BLUE=[
    HOMME_MAILLOTS_BLUE_1,
    HOMME_MAILLOTS_BLUE_2,
    HOMME_MAILLOTS_BLUE_3,
    HOMME_MAILLOTS_BLUE_4,
    HOMME_MAILLOTS_BLUE_5
]


export const images_vetements_HOMME_MAILLOTS_BLACK=[
    HOMME_MAILLOTS_BLACK_1,
    HOMME_MAILLOTS_BLACK_2,
    HOMME_MAILLOTS_BLACK_3,
    HOMME_MAILLOTS_BLACK_4,
    HOMME_MAILLOTS_BLACK_5,
]


export const images_vetements_HOMME_PANTALON_BRETELLES_WHITE=[
    HOMME_PANTALON_BRETELLES_WHITE_1,
    HOMME_PANTALON_BRETELLES_WHITE_2,
    HOMME_PANTALON_BRETELLES_WHITE_3,
    HOMME_PANTALON_BRETELLES_WHITE_4,
    HOMME_PANTALON_BRETELLES_WHITE_5,
]


export const images_vetements_HOMME_PANTALON_BRETELLES_BLACK=[
    HOMME_PANTALON_BRETELLES_BLACK_1,
    HOMME_PANTALON_BRETELLES_BLACK_2,
    HOMME_PANTALON_BRETELLES_BLACK_3,
    HOMME_PANTALON_BRETELLES_BLACK_4,
    HOMME_PANTALON_BRETELLES_BLACK_5,

]


export const images_vetements_HOMME_SWEATS_TSHIRTS_BLACK=[
    HOMME_SWEATS_TSHIRTS_BLACK_1,
    HOMME_SWEATS_TSHIRTS_BLACK_2,
    HOMME_SWEATS_TSHIRTS_BLACK_3,
    HOMME_SWEATS_TSHIRTS_BLACK_4,
]

export const images_vetements_HOMME_SWEATS_TSHIRTS_PETROLE=[
    HOMME_SWEATS_TSHIRTS_PETROLE_1,
    HOMME_SWEATS_TSHIRTS_PETROLE_2,
    HOMME_SWEATS_TSHIRTS_PETROLE_3,
    HOMME_SWEATS_TSHIRTS_PETROLE_4,
]


export const images_vetements_HOMME_CASQUETTES_BASIQUES_BLACK=[
    HOMME_CASQUETTES_BASIQUES_BLACK_1
]


export const images_vetements_HOMME_CASQUETTES_BASIQUES_GRIS=[
    HOMME_CASQUETTES_BASIQUES_GRIS_1
]


export const images_vetements_FEMME_MAILLOTS_BLUE=[
    FEMME_MAILLOTS_BLUE_1,
    FEMME_MAILLOTS_BLUE_2,
    FEMME_MAILLOTS_BLUE_3,
    FEMME_MAILLOTS_BLUE_4,
]


export const images_vetements_FEMME_MAILLOTS_BLACK=[
    FEMME_MAILLOTS_BLACK_1,
    FEMME_MAILLOTS_BLACK_2,
    FEMME_MAILLOTS_BLACK_3,
    FEMME_MAILLOTS_BLACK_4,
]


export const images_vetements_FEMME_PANTALON_BRETELLES_WHITE=[
    FEMME_PANTALON_BRETELLES_WHITE_1,
    FEMME_PANTALON_BRETELLES_WHITE_2,
]

export const images_vetements_FEMME_PANTALON_BRETELLES_BLACK=[
    FEMME_PANTALON_BRETELLES_BLACK_1,
    FEMME_PANTALON_BRETELLES_BLACK_2,
]


export const images_vetements_FEMME_SWEATS_TSHIRTS_BLACK=[
    FEMME_SWEATS_TSHIRTS_BLACK_1,
    FEMME_SWEATS_TSHIRTS_BLACK_2,
    FEMME_SWEATS_TSHIRTS_BLACK_3,
    FEMME_SWEATS_TSHIRTS_BLACK_4,
]

export const images_vetements_FEMME_SWEATS_TSHIRTS_WHITE=[
    FEMME_SWEATS_TSHIRTS_WHITE_1,
    FEMME_SWEATS_TSHIRTS_WHITE_2,
    FEMME_SWEATS_TSHIRTS_WHITE_3,
    FEMME_SWEATS_TSHIRTS_WHITE_4,
]

export const images_gants_GRAVITY_OLIVE=[
    GRAVITY_OLIVE_1,
    GRAVITY_OLIVE_2,
    GRAVITY_OLIVE_3,
    GRAVITY_OLIVE_4,
    GRAVITY_OLIVE_5,
]

export const images_gants_GRAVITY_BLUE=[
    GRAVITY_BLUE_1,
    GRAVITY_BLUE_2,
    GRAVITY_BLUE_3,
    GRAVITY_BLUE_4,
    GRAVITY_BLUE_5,
]

export const images_gants_RACE_BLANC=[
    RACE_BLANC_1,
    RACE_BLANC_2,
    RACE_BLANC_3,
    RACE_BLANC_4
]

export const images_gants_RACE_BLACK=[
    RACE_BLACK_1,
    RACE_BLACK_2,
    RACE_BLACK_3,
    RACE_BLACK_4,
    RACE_BLACK_5,
]


export const images_chaussures_MTB_PEACK_PRO_BLACK=[
    MTB_PEACK_PRO_BLACK_1,
    MTB_PEACK_PRO_BLACK_2,
    MTB_PEACK_PRO_BLACK_3,
    MTB_PEACK_PRO_BLACK_4,
    MTB_PEACK_PRO_BLACK_5
]


export const images_chaussures_MTB_PEACK_BLACK=[
    MTB_PEACK_BLACK_1,
    MTB_PEACK_BLACK_2,
    MTB_PEACK_BLACK_3,
    MTB_PEACK_BLACK_4,
    MTB_PEACK_BLACK_5,
]
export const images_chaussures_ALL_TERRAIN_OX_PRO_GREY=[
    ALL_TERRAIN_OX_PRO_GREY_1,
    ALL_TERRAIN_OX_PRO_GREY_2,
    ALL_TERRAIN_OX_PRO_GREY_3,
    ALL_TERRAIN_OX_PRO_GREY_4,
    ALL_TERRAIN_OX_PRO_GREY_5,
]


export const images_chaussures_ALL_TERRAIN_OX_GREY=[
    ALL_TERRAIN_OX_GREY_1,
    ALL_TERRAIN_OX_GREY_2,
    ALL_TERRAIN_OX_GREY_3,
    ALL_TERRAIN_OX_GREY_4,
    ALL_TERRAIN_OX_GREY_5,
]